name: WAY-AI
run-name: WAY AI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/way-ai:${{ github.sha }}
      
        
  # update-deployment-file:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout argo-manifest repository
  #     uses: actions/checkout@v3
  #     with:
  #       repository: ${{ secrets.USERNAME }}/argo-manifest
  #       token: ${{ secrets.PAT }}

  #   - name: Install yq
  #     run: sudo snap install yq

  #   - name: Update image in rollout file
  #     run: |
  #       yq e '.spec.template.spec.containers[0].image = "${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/way-ai:${{ github.sha }}"' ./AI/way-be-aiservice-rollout.yaml -i 
  #   - name: Commit and Push changes
      
  #     run: |
  #       git config --global user.email "${{ secrets.EMAIL }}"
  #       git config --global user.name "${{ secrets.USERNAME }}"
  #       git add .
  #       git commit -m "[CI/CD] Update way-be-aiservice-rollout.yaml"
  #       git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USERNAME }}/argo-manifest
  #       git push --set-upstream origin HEAD