name: WAY-AI
run-name: WAY AI
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Qemu
      uses: docker/setup-qemu-action@v2

    - name: Build Docker image
      run: |
        cd ..
        docker build -t way-ai .

    - name: Login to Docker Hub
      run: docker login gcu-dto-dev.kr-central-2.kcr.dev --username ${{ secrets.ACCESS_KEY }} --password ${{ secrets.ACCESS_SECRET_KEY }}

    - name: Tag Docker image
      run: docker tag way-ai gcu-dto-dev.kr-central-2.kcr.dev/way-ai/way-ai:${{ github.sha }}

    - name: Push Docker image to registry
      run: docker push gcu-dto-dev.kr-central-2.kcr.dev/way-ai/way-ai:${{ github.sha }}

  update-deployment-file:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
    - name: Checkout argo-manifest repository
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.USERNAME }}/argo-manifest
        token: ${{ secrets.PAT }}

    - name: Install yq
      run: sudo snap install yq

    - name: Update image in rollout file
      run: |
        yq e '.spec.template.spec.containers[0].image = "${{ secrets.PROJECT_NAME }}.kr-central-2.kcr.dev/${{ secrets.REPOSITORY_NAME }}/way-ai:${{ github.sha }}"' ./AI/way-be-aiservice-rollout.yaml -i 
    - name: Commit and Push changes
      
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
        git add .
        git commit -m "[CI/CD] Update way-be-aiservice-rollout.yaml"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ secrets.USERNAME }}/argo-manifest
        git push --set-upstream origin HEAD